services:
  db:
    image: luukien/postgres-data:v5
#    volumes:
#      - postgres-groupweb:/var/lib/postgresql/data/ #(1)
    restart: always
    networks:
      - my-web-network #(2)
    environment:
      POSTGRES_PASSWORD: Luudinhkien_2003
      POSTGRES_USER: postgres
      POSTGRES_DB: groupweb2
    ports:
      - "5433:5432"
    container_name: postgres-data

  app:
    image: luukien/backend:v4
    restart: on-failure
    build: #(4)
      context: .
      dockerfile: Dockerfile
    networks:
      - my-web-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod #(3)
    ports:
      - "8088:8088"
    container_name: backend
    depends_on:
      - db

  frontend:
    image: luukien/frontend:v5
    restart: on-failure
    networks:
      - my-web-network
    ports:
      - "4003:80"
    depends_on:
      - app
    container_name: frontend

  mail-sever:
    image: luukien/mail-server:v3
    restart: always
    networks:
      - my-web-network
    ports:
      - "8087:8087"
      - "8887:8887"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    container_name: mail-server

volumes:
  postgres-groupweb:
networks:
  my-web-network:
    driver: bridge
